common\interfaces\src\gw.types.ts 	Needed "type" in the export
core\toast\src\toast-message.model.ts
	toast-message.model.ts(15, 15): 'message' is declared here.
	removed pulic from the constructors and put them in the body, the constructor now sets the properties

core\name-value-pair\src\c\manage-name-value-pairs\manage-name-value-pairs.component.ts
	Property '_NameValuePairService' is used before its initialization.
	now sets it in the constructor

core\account\src\c\account-details\account-details.component.ts
	Property '_AccountSvc' is used before its initialization.
	Now sets the following in the constructor:
		pickListTableContentsBackground
		pickListTableContentsFont
		pickListTableHeaderBackground

core\function\src\c\function-details\function-details.component.ts
	Property '_AccountSvc' is used before its initialization.
	Now sets the following in the constructor:
		clientChoices

Recieved the error in the following files:
	Error: Property 'firstLevel' will overwrite the base property in 'NavigationComponentBase'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.

	vertical.component.ts
	hierarchical-horizontal.component.ts
	hierarchical-vertical.component.ts
	horizontal.component.ts

	Now adds a value to the firstLevel property:
		@ViewChild('firstLevel', { static: false }) override firstLevel: ElementRef<HTMLUListElement> = {} as ElementRef<HTMLUListElement>;